### ISSUE TITLE
Support job resource configuration

### ISSUE THREAD

**Issue by regadas** [spotify/flyte-flink-plugin#23]
Job submitter resources are currently hard coded to:

```
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
```

For some jobs this might result in:

```
java.lang.OutOfMemoryError: Java heap space
```
